### ISSUE TITLE
HTML Reporter/Databricks reporter

### ISSUE THREAD

**Issue by eyaltrabelsi** [FRosner/drunken-data-quality#146]
Hi I am using databricks and your package is very useful.

I managed to make zepplin reporter work on databricks using something like:

> import java.io._
> def Databrick
> var htmlOutput = new ByteArrayOutputStream();
> val zepplinReporter: Reporter = ZeppelinReporter(new PrintStream(htmlOutput))
> 
> Runner.run(Seq(check), Seq(zepplinReporter))
> val html_content = htmlOutput.toString.stripPrefix("%html")
> displayHTML(html_content)

I think it can be beneficial to other people and i and i am wondering whether you prefer the pull request as documentation or reporter like this one

**Comment by FRosner** [comment]
Thanks @eyaltrabelsi!

I see that you basically just stripped `%html` and then used the HTML output. For Zeppelin there was a trick necessary when printing multiple check results in the same cell. Can you try adding another check to the sequence and see if the output is still good?

Where does the `displayHTML` function come from? Is it Databricks built-in?

**Comment by eyaltrabelsi** [comment]
@FRosner 

- Regarding the %html basically you are right there are the small games of the sending ByteArrayOutputStream as an input.
- I have no problem doing more checks, I just want to know for PR purposes if its worthy of its own reporter in you opinion. If not I know it can be super beneficial as a documentation the readme.
- Regarding displayHTML its equivalent to %html in zeplin more less but its a function and not a cell markdown;

**Comment by FRosner** [comment]
Thanks @eyaltrabelsi,

Just to clarify. In which namespace does `displayHTML` live? Is it imported automatically? 

Also I am asking about the multiple checks because the HTML looks different for the second check. So you are telling me that when running multiple checks in the same cell, the output still looks good? Just out of curiosity, can you attach a screenshot of the [checks from the README](https://github.com/FRosner/drunken-data-quality/#getting-started) run with your Databricks reporter?

I'd love to have it as a separate class, especially as the Zeppelin reporter might change if Zeppelin changes its way of rendering. I wouldn't like to have a dependency there. What we can do to reduce code duplication is to factor out the method that generates the HTML code and have the Zeppelin and Databricks reporters only put the required surrounding code.

Let me know what you think.
