### ISSUE TITLE
Show table name

### ISSUE THREAD

**Issue by ghost** [FRosner/drunken-data-quality#22]
The following code

```
val t = hiveContext.table("myTableName")
Check(t)....run
```

will display

```
Checking [column1: string, column2: string, ... columnN: string]
```

It would be more user-frienldy to show:

```
Checking databaseName.myTableName:
```

**Comment by FRosner** [comment]
@mfsny thanks for the issue. Unfortunately I did not find a way to retrieve the table name from the SQL context. This is probably the case because it works for all data frames, also the ones not coming from a Hive table.

My suggestion would be to either have a an optional parameter containing a name to display (this issue). We can then also provide another constructor that takes a SQL context and a table name to check from (#24).

What do you think?

**Comment by ghost** [comment]
Would vote for #24 . The solution with additional parameter is a reasonable workaround until then.

**Comment by FRosner** [comment]
@mfsny I do not see it as a workaround but as a lower level method to create readable checks on data frames where you don't have a table and database because you created them on the fly. So we actually need both.
