### ISSUE TITLE
Print also the merge rate within the "isJoinableWith" check.

### ISSUE THREAD

**Issue by zhdchen** [FRosner/drunken-data-quality#35]
Please also print the merge rate for the "isJoinableWith" check:
count (distinct <join column(s)>) AFTER join for base table
count (distinct <join column(s)>) BEFORE join for base table
merge rate = count (distinct <join column(s)>) AFTER join / count (distinct <join column(s)>) BEFORE join

Currently in the version 2.10-1.2.0 only distinct row number printed.

**Comment by FRosner** [comment]
@zhdchen can you provide a simple example of two tables and document the current as well as the expected results after the change?

**Comment by zhdchen** [comment]
@FRosner Suppose we have two tables a and b
table a
num
1
2
2
3
3
3
4

table b
num name
1       a
1       b
1       c
2       a
2       d
3       f

Check(a).isJoinableWith(b, "num" -> "num").run
should return following:
Distinct amount of num in table a: 4; Distinct amount of num after join: 3; Merge rate: 75%
This means 75% of the distinct num in table a can find join result in table b.

The join condition can also be multiple columns.

**Comment by FRosner** [comment]
Sounds reasonable. @mfsny what do you think? @zhdchen can you provide a pull request?

**Comment by FRosner** [comment]
@zhdchen keep in mind that computing the distinct count before the join requires a bit of extra work and will take some extra time. But I think it shouldn't be a big deal as it is a rather simple operation.

**Comment by ghost** [comment]
@FRosner I implemented a solution with the help of @zhdchen . As soon as I have access, I will push and create a pull request.

**Comment by FRosner** [comment]
@bkomboz please fork and create a pull request. Keep in mind to create the pr from a non-master branch so you don't interfere with #23.

**Comment by FRosner** [comment]
Thanks for picking this up @bkomboz. I put it into 2.1.0.

**Comment by FRosner** [comment]
@zhdchen can you please test the implementation in #64 and tell me whether it matches your expectations? If it looks good to you, we can merge it.

**Comment by FRosner** [comment]
@bkomboz can you please tell @zhdchen to check if the implementation matches his expectations? Otherwise I don't want to merge it.

**Comment by zhdchen** [comment]
@FRosner @bkomboz Yep, requirements are totally fulfilled. Thanks!

**Comment by FRosner** [comment]
@zhdchen did you actually test it? :)

**Comment by FRosner** [comment]
@bkomboz what is the semantics of the merge rate when the reference table contains multiple entries?

So what is the expected merge rate for the following example?

```
val base = makeIntegerDf(List(1, 2, 3))
val ref = makeIntegerDf(List(1, 1, 2, 5))
val check = Check(base).isJoinableWith(ref, "column" -> "column")
```

Is the merge rate commutative? So will should `Check(base).isJoinableWith(ref, "column" -> "column")` give the same merge rate result as `Check(ref).isJoinableWith(base, "column" -> "column")` for all possible reference and base tables? It has to be, because the join operator is commutative.

Also we should add test cases for these parts.

**Comment by ghost** [comment]
I would say yes: The expected merge rate is commutative. And multiple entries should not matter. I can add tests for these things but I don't know if I will manage today or tomorrow.

**Comment by FRosner** [comment]
@bkomboz while I agree with the first point (and will add test cases to verify whether your implementation is correct), I am not sure about the second one.

If I have duplicate foreign keys in the base table (so a one-to-many relationship), I could also expect them to count into the merge rate. E.g., if I have a transaction table and a customer table and then want to see if I can join the two. Customer 1 has 99 transactions and can be found in the customer table, while customer 2 has only 1 transaction but cannot be found. So the merge rate could be either 50% or 99%. Both scenarios make sense, they just have different semantics (one is the merge rate of transactions, the other one of bills). So maybe this could also be an argument why it should **not** be commutative?

What do you think?

**Comment by ghost** [comment]
@FRosner I understand your point. Reading again the original request by @zhdchen, I understand it as a request for a cummutative implementation which would/should return 50% in your example. This is what I would implement. However, we could also print both versions, because as you said, both make sense and one could also be interested in the second number (99%).

**Comment by FRosner** [comment]
Makes sense to me @bkomboz. I will write the tests this weekend and I think we should implement it the 50%-way. But it needs to be documented well. I'll update you once the tests are implemented and we'll see whether the current implementation works :)

**Comment by ghost** [comment]
@frosner: Alright, thanks. I hope it works. ;-)

**Comment by FRosner** [comment]
@bkomboz I pushed a new proposal. I changed the name of "merge rate" to "unmatched keys percentage", because this seems to be the most reasonable to me when I want to have a weak foreign key check.

So should the number be computed based on the distinct complete rows, or distinct key column records?

### Example

**Base Table**

| Column 1 | Column 2 |
| --- | --- |
| 1 | a |
| 1 | b |
| 2 | c |

**Reference Table**

| Column 1 | Column 2 |
| --- | --- |
| 1 | test1 |
| 2 | test2 |

Should the "merge rate" based on Column 1 be 50% or 67% in this case?
